env:
  node: true
  es2022: true
  jest: true
extends:
  - 'eslint:recommended'
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2022
plugins:
  - '@typescript-eslint'
rules: {}
