version: "3"

services:
  mysql:
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: "admin12345"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin12345"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
